name: 'basket_craft_dbt'
version: '1.0'

profile: 'basket_craft_dbt'

config-version: 2

models:
  basket_craft:
    staging:
      +schema: staging
      +materialized: view
    warehouse:
      +schema: warehouse
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
