name: 'basket_craft_data_pipeline'
version: '1.0'

profile: 'basket_craft_dbt'

config-version: 2

models:
  basket_craft_data_pipeline:
    staging:
      materialized: view
    warehouse:
      materialized: table

