name: Extract and Load Basket Craft Website Sessions

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:  

jobs:
  run_etl:
    runs-on: ubuntu-latest

env:
  MYSQL_USER:    ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_HOST:    ${{ secrets.MYSQL_HOST }}
  MYSQL_DB:      ${{ secrets.MYSQL_DB }}
  PG_USER:       ${{ secrets.PG_USER }}
  PG_PASSWORD:   ${{ secrets.PG_PASSWORD }}
  PG_HOST:       ${{ secrets.PG_HOST }}
  PG_DB:         ${{ secrets.PG_DB }}

steps:
  - uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: pip install pandas SQLAlchemy pymysql psycopg2-binary

  - name: Run ETL script
    run: python elt/basket_craft_website_sessions_extract_load_raw.py
